"""Add preference manager tables

Revision ID: 956cd4f9c8eb
Revises: 
Create Date: 2026-02-07 22:21:46.078964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '956cd4f9c8eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 为现有 User 表添加 is_admin 字段
    # 对于 SQLite，需要分步执行：添加可空列，更新数据，然后设置为非空
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='0'))
    op.execute("UPDATE users SET is_admin = 0 WHERE is_admin IS NULL")
    # 使用 batch_alter_table 来更改列约束（SQLite 需要）
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_admin', nullable=False)

    # 创建 scraper_follows 表（平台抓取账号列表）
    op.create_table(
        'scraper_follows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=15), nullable=False),
        sa.Column('added_at', sa.DateTime(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('added_by', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_index('idx_scraper_follows_active', 'scraper_follows', ['is_active'], unique=False)
    op.create_index('idx_scraper_follows_username', 'scraper_follows', ['username'], unique=False)

    # 创建 filter_rules 表（过滤规则）
    op.create_table(
        'filter_rules',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('filter_type', sa.String(length=20), nullable=False),
        sa.Column('value', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "filter_type IN ('keyword', 'hashtag', 'content_type')",
            name='ck_filter_rules_type'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filter_rules_type', 'filter_rules', ['filter_type'], unique=False)
    op.create_index('idx_filter_rules_user_id', 'filter_rules', ['user_id'], unique=False)

    # 创建 twitter_follows 表（用户关注列表）
    op.create_table(
        'twitter_follows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=15), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='5'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            'priority BETWEEN 1 AND 10',
            name='ck_twitter_follows_priority_range'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'username', name='uq_twitter_follows_user_username')
    )
    op.create_index('idx_twitter_follows_priority', 'twitter_follows', ['priority'], unique=False)
    op.create_index('idx_twitter_follows_user_id', 'twitter_follows', ['user_id'], unique=False)
    op.create_index('idx_twitter_follows_username', 'twitter_follows', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除新创建的表
    op.drop_index('idx_twitter_follows_username', table_name='twitter_follows')
    op.drop_index('idx_twitter_follows_user_id', table_name='twitter_follows')
    op.drop_index('idx_twitter_follows_priority', table_name='twitter_follows')
    op.drop_table('twitter_follows')

    op.drop_index('idx_filter_rules_user_id', table_name='filter_rules')
    op.drop_index('idx_filter_rules_type', table_name='filter_rules')
    op.drop_table('filter_rules')

    op.drop_index('idx_scraper_follows_username', table_name='scraper_follows')
    op.drop_index('idx_scraper_follows_active', table_name='scraper_follows')
    op.drop_table('scraper_follows')

    # 删除 is_admin 字段
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
